[package]
name = "akroyd-test"
version = "0.1.0"
edition = "2021"

[dependencies]
akroyd = { path = "../akroyd", features = ["derive", "postgres"] }

postgres = "0.19"
tokio-postgres = "0.7"
tokio = { version = "1", features = ["full"] }
