[workspace]
resolver = "2"

members = [
    "aykroyd",
    "aykroyd-derive",
    "aykroyd-migrate",
    "bb8-aykroyd",
    "deadpool-aykroyd",
    "example",
    "myg",
]

default-members = [
    "aykroyd",
    "aykroyd-derive",
    "aykroyd-migrate",
    "myg",
]
