[workspace]
members = [
    "aykroyd",
    "aykroyd-derive",
    "aykroyd-migrate",
    "bb8-aykroyd",
    "example",
]

default-members = [
    "aykroyd",
    "aykroyd-derive",
    "aykroyd-migrate",
]
