[workspace]
resolver = "2"

members = [
    "aykroyd",
    "aykroyd-derive",
    "bb8-aykroyd",
    "deadpool-aykroyd",
    "r2d2-aykroyd",
]

default-members = [
    "aykroyd",
    "aykroyd-derive",
]
