[package]
name = "akroyd-test-sync"
version = "0.1.0"
edition = "2021"

[dependencies]
akroyd = { path = "../akroyd", features = ["sync", "derive"] }
akroyd-test = { path = "../akroyd-test" }

postgres = "0.19"

[workspace]
members = ["."]
