[package]
name = "example-async"
version = "0.1.0"
edition = "2021"

[dependencies]
aykroyd = { path = "../../aykroyd", features = ["async"] }
common = { path = "../common" }

tokio-postgres = "0.7"
tokio = { version = "1", features = ["full"] }
