[package]
name = "deadpool-aykroyd"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
aykroyd = { version = "0.1", features = ["async"], path = "../aykroyd" }
deadpool = "0.9"
deadpool-postgres = "0.10"
tokio = "1"
tokio-postgres = "0.7"
