[package]
name = "aykroyd-v2"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
mysql = { version = "24", optional = true }
rusqlite = { version = "0.30", optional = true }
tokio-postgres = "0.7"
