[package]
name = "r2d2-aykroyd"
version = "0.1.0"
edition = "2021"

[dependencies]
aykroyd = { version = "0.2", features = ["sync"], path = "../aykroyd" }
r2d2 = "0.8"
r2d2_postgres = "0.18"
postgres = "0.19"
